Fix typo introduced in #55125 (#55329)
```
error: unexpected argument '--no-python-download' found
tip: a similar argument exists: '--no-python-downloads'
```